# Generated by Django 5.1.4 on 2025-02-03 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('isMoving', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('center_latitiude', models.FloatField(default=0.0)),
                ('center_longitude', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='NoFly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.map')),
                ('noflies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.nofly')),
            ],
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('noflies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.nofly')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='drone',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.map'),
        ),
        migrations.AddField(
            model_name='partition',
            name='drone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.drone'),
        ),
        migrations.AddField(
            model_name='partition',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.map'),
        ),
        migrations.AddField(
            model_name='point',
            name='partitions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.partition'),
        ),
        migrations.AddField(
            model_name='nofly',
            name='points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.point'),
        ),
    ]
