# Generated by Django 5.1.4 on 2025-02-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_drone_map_nofly_partition_point_delete_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='noflies',
            new_name='nofly',
        ),
        migrations.RemoveField(
            model_name='map',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nofly',
            name='noflies',
        ),
        migrations.RemoveField(
            model_name='nofly',
            name='points',
        ),
    ]
