# Generated by Django 5.1.4 on 2025-02-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_noflies_point_nofly_remove_map_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='center_latitiude',
            new_name='center_latitude',
        ),
    ]
