# Generated by Django 5.1.4 on 2025-02-14 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_center_latitiude_map_center_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='nofly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.nofly'),
        ),
        migrations.AlterField(
            model_name='point',
            name='partitions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.partition'),
        ),
    ]
