# Generated by Django 5.1.4 on 2025-02-14 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_point_nofly_alter_point_partitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drones', to='db.map'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='drone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partition', to='db.drone'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='db.map'),
        ),
        migrations.AlterField(
            model_name='point',
            name='nofly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='db.nofly'),
        ),
        migrations.AlterField(
            model_name='point',
            name='partitions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='db.partition'),
        ),
    ]
