# Generated by Django 5.1.4 on 2025-02-27 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_drone_map_alter_partition_drone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='drone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='db.drone'),
        ),
    ]
