# Generated by Django 5.1.4 on 2025-02-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_partition_drone'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
