# Generated by Django 5.1.4 on 2025-02-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_partition_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='type',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
