# Generated by Django 5.1.4 on 2025-03-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_partition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drone',
            name='longitude',
            field=models.IntegerField(default=0),
        ),
    ]
