# Generated by Django 5.1.4 on 2025-04-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_alter_drone_latitude_alter_drone_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='num_drones',
            field=models.IntegerField(default=4),
        ),
    ]
